server:
  port: 9528
  servlet:
    context-path: /
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: exercise-product    #全部小写，注册于eureka server上的服务名称，不写名称显示为UNKNOW
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.190.30.116:3306/exercise?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

#mybatis配置
mybatis:
  mapperLocations: classpath:mapper/*.xml
