spring:
  application:
    name: exercise-eureka-peer2
    profiles: peer2
#  security:
#    user:
#      name: root        # 用户名
#      password: 123456   # 密码

server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
    register-with-eureka: false
    fetch-registry: false