server:
  port: 9527
  servlet:
    context-path: /
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
  instance:
    prefer-ip-address: true    #访问路径可以显示IP地址

spring:
  thymeleaf:
    cache: false
  application:
    name: exercise-user
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.190.50.187:3306/tmc_db?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false

  activemq:
    # broker地址，默认端口是61616
    broker-url: tcp://192.190.50.187:61616
    # 信任所有的包，这个配置是为了支持发送对象消息
    packages:
      trust-all: true
    # ActiveMQ的用户名
    user: admin
    # ActiveMQ的密码
    password: admin
    # queue和topic不能同时使用，使用topic的时候，把下面这行解除注释
    jms:
      pub-sub-domain: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:mybatis-mappers/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0

