server:
  port: 9527
  servlet:
    context-path: /
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
  instance:
    prefer-ip-address: true
#  instance:
#    prefer-ip-address: true    #访问路径可以显示IP地址

spring:
  application:
    name: exercise-user
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/exercise?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
#mybatis配置
mybatis:
  mapperLocations: classpath:mapper/*.xml

info:
  app.name: exercise-user-9527

