server:
  port: 9527
  servlet:
    context-path: /
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
#  instance:
#    prefer-ip-address: true    #访问路径可以显示IP地址

spring:
  application:
    name: exercise-user
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.100.35:3306/exercise?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

#mybatis配置
mybatis:
  mapperLocations: classpath:mapper/*.xml

info:
  app.name: exercise-user-9527

