server:
  port: 8000

#服务的名称
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/ # 搜索src/main/resource 下的config文件夹下的文件
  application:
    name: exercise-config
  profiles:
    active: native  # 配置使用本地储存

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/

